language : c

sudo: false

env:
 - ASAN_OPTIONS=abort_on_error=0 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_SKIP_CPUFREQ=1 AFL_NO_UI=1 AFL_EXIT_WHEN_DONE=1 AFL_STOP_MANUALLY=1

script:
  - make
  - ./test.sh
  - ./fuzz_test.sh

notifications:
  email:
    recipients:
      - qpalzmm22@gmail.com
